### ISSUE TITLE
AttributeError: 'unittest.TestCase' object has no attribute 'assert_match'

### ISSUE THREAD

**Issue by tw00** [joseph-roitman/pytest-snapshot#69]
Hi, it seems like some additional setup is required.

Does `pytest-snapshot` still work with `pytest 7.4.3`?

I'm using Python 3.11.6 and pytest-snapshot~=0.9.0.

**Comment by tw00** [comment]
Ok looks like `pytest-snapshot` can not be used with `unittest`.
